package com.example.a12260.szh.Entity;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.a12260.szh.Entity.DailyRecord;
import com.example.a12260.szh.Entity.MonthRecord;
import com.example.a12260.szh.Entity.PackageApp;
import com.example.a12260.szh.Entity.WeekRecord;
import com.example.a12260.szh.Entity.Plan;
import com.example.a12260.szh.Entity.PlanApp;

import com.example.a12260.szh.Entity.DailyRecordDao;
import com.example.a12260.szh.Entity.MonthRecordDao;
import com.example.a12260.szh.Entity.PackageAppDao;
import com.example.a12260.szh.Entity.WeekRecordDao;
import com.example.a12260.szh.Entity.PlanDao;
import com.example.a12260.szh.Entity.PlanAppDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig dailyRecordDaoConfig;
    private final DaoConfig monthRecordDaoConfig;
    private final DaoConfig packageAppDaoConfig;
    private final DaoConfig weekRecordDaoConfig;
    private final DaoConfig planDaoConfig;
    private final DaoConfig planAppDaoConfig;

    private final DailyRecordDao dailyRecordDao;
    private final MonthRecordDao monthRecordDao;
    private final PackageAppDao packageAppDao;
    private final WeekRecordDao weekRecordDao;
    private final PlanDao planDao;
    private final PlanAppDao planAppDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        dailyRecordDaoConfig = daoConfigMap.get(DailyRecordDao.class).clone();
        dailyRecordDaoConfig.initIdentityScope(type);

        monthRecordDaoConfig = daoConfigMap.get(MonthRecordDao.class).clone();
        monthRecordDaoConfig.initIdentityScope(type);

        packageAppDaoConfig = daoConfigMap.get(PackageAppDao.class).clone();
        packageAppDaoConfig.initIdentityScope(type);

        weekRecordDaoConfig = daoConfigMap.get(WeekRecordDao.class).clone();
        weekRecordDaoConfig.initIdentityScope(type);

        planDaoConfig = daoConfigMap.get(PlanDao.class).clone();
        planDaoConfig.initIdentityScope(type);

        planAppDaoConfig = daoConfigMap.get(PlanAppDao.class).clone();
        planAppDaoConfig.initIdentityScope(type);

        dailyRecordDao = new DailyRecordDao(dailyRecordDaoConfig, this);
        monthRecordDao = new MonthRecordDao(monthRecordDaoConfig, this);
        packageAppDao = new PackageAppDao(packageAppDaoConfig, this);
        weekRecordDao = new WeekRecordDao(weekRecordDaoConfig, this);
        planDao = new PlanDao(planDaoConfig, this);
        planAppDao = new PlanAppDao(planAppDaoConfig, this);

        registerDao(DailyRecord.class, dailyRecordDao);
        registerDao(MonthRecord.class, monthRecordDao);
        registerDao(PackageApp.class, packageAppDao);
        registerDao(WeekRecord.class, weekRecordDao);
        registerDao(Plan.class, planDao);
        registerDao(PlanApp.class, planAppDao);
    }
    
    public void clear() {
        dailyRecordDaoConfig.clearIdentityScope();
        monthRecordDaoConfig.clearIdentityScope();
        packageAppDaoConfig.clearIdentityScope();
        weekRecordDaoConfig.clearIdentityScope();
        planDaoConfig.clearIdentityScope();
        planAppDaoConfig.clearIdentityScope();
    }

    public DailyRecordDao getDailyRecordDao() {
        return dailyRecordDao;
    }

    public MonthRecordDao getMonthRecordDao() {
        return monthRecordDao;
    }

    public PackageAppDao getPackageAppDao() {
        return packageAppDao;
    }

    public WeekRecordDao getWeekRecordDao() {
        return weekRecordDao;
    }

    public PlanDao getPlanDao() {
        return planDao;
    }

    public PlanAppDao getPlanAppDao() {
        return planAppDao;
    }

}
